// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cqsdxzziodtprpsyrrgj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNxc2R4enppb2R0cHJwc3lycmdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3OTM0OTksImV4cCI6MjA2NjM2OTQ5OX0.bC6J6qjdZGN9V6nuE1c_CM_FwXocZIYUKb80Ggb9zn0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);